// flow-typed signature: 1c2a34faeafb73fdc295a048e83a502c
// flow-typed version: <<STUB>>/micro_v^8.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micro/bin/micro' {
  declare module.exports: any;
}

declare module 'micro/lib/error' {
  declare module.exports: any;
}

declare module 'micro/lib/handler' {
  declare module.exports: any;
}

declare module 'micro/lib/help' {
  declare module.exports: any;
}

declare module 'micro/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micro/bin/micro.js' {
  declare module.exports: $Exports<'micro/bin/micro'>;
}
declare module 'micro/lib/error.js' {
  declare module.exports: $Exports<'micro/lib/error'>;
}
declare module 'micro/lib/handler.js' {
  declare module.exports: $Exports<'micro/lib/handler'>;
}
declare module 'micro/lib/help.js' {
  declare module.exports: $Exports<'micro/lib/help'>;
}
declare module 'micro/lib/index.js' {
  declare module.exports: $Exports<'micro/lib/index'>;
}
